In [13]:
import pandas as pd
import numpy as  np

df = pd.read_csv('swiggy_delivery_data.csv')
df.dropna(axis=0, how='all')
df.dropna(axis=1, how='all')

df['order_time'] = pd.to_datetime(df['order_time'], errors='coerce', format='%Y/%m/%d %H:%M')
df['delivery_time'] = pd.to_datetime(df['delivery_time'], errors='coerce', format='%d-%m-%Y %H:%M:%S')

In [31]:
df['Order_Hour'] = df['order_time'].dt.hour
df['Day_Name'] = df['order_time'].dt.day_name()

def check_weekend(a):
    if (a['Day_Name']=="Saturday") or (a['Day_Name']=="Sunday"):
        return 1
    else:
        return 0

df['IS_WeekEnd'] = df.apply(lambda x : check_weekend(x), axis=1)
df['Order_Month'] = df['order_time'].dt.to_period("M")

df['Delivery_Duration'] = (df['delivery_time'] - df['order_time']).dt.total_seconds() / 60

,order_id,zone,restaurant,delivery_partner,order_time,delivery_time,Delivery Delay (mins),Cancelled (1/0),Customer Rating,Order_Hour,Day_Name,IS_WeekEnd,Order_Month,Delivery_Duration
0,ORD1000,West,Restaurant_3,DP_6,2023-07-11 23:24:00,2023-07-12 00:06:00,12,0,4.6,23.0,Tuesday,0,2023-07,42.0
1,ORD1001,Central,Restaurant_7,DP_37,2023-07-11 03:46:00,2023-07-11 04:31:00,15,0,4.9,3.0,Tuesday,0,2023-07,45.0
2,ORD1002,East,Restaurant_27,DP_10,2023-07-20 12:52:00,2023-07-20 13:34:00,12,0,3.5,12.0,Thursday,0,2023-07,42.0
3,ORD1003,Central,Restaurant_28,DP_40,2023-07-06 12:31:00,2023-07-06 13:05:00,4,0,3.5,12.0,Thursday,0,2023-07,34.0
4,ORD1004,Central,Restaurant_22,DP_7,2023-07-05 11:29:00,2023-07-05 12:18:00,19,0,4.9,11.0,Wednesday,0,2023-07,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2195,ORD3195,West,Restaurant_9,DP_25,2023-07-26 03:19:00,2023-07-26 04:01:00,12,0,2.9,3.0,Wednesday,0,2023-07,42.0
2196,ORD3196,South,Restaurant_25,DP_30,2023-07-16 21:52:00,2023-07-16 22:30:00,8,0,3.9,21.0,Sunday,1,2023-07,38.0
2197,ORD3197,Central,Restaurant_29,DP_29,2023-07-26 15:19:00,2023-07-26 15:50:00,1,0,4.5,15.0,Wednesday,0,2023-07,31.0
2198,ORD3198,West,Restaurant_25,DP_20,2023-07-26 16:21:00,2023-07-26 17:13:00,22,0,4.0,16.0,Wednesday,0,2023-07,52.0
2199,ORD3199,Central,Restaurant_28,DP_21,2023-07-11 13:55:00,2023-07-11 14:35:00,10,0,3.3,13.0,Tuesday,0,2023-07,40.0